language: python
python:
  - '2.7'
  - '2.6'
script: 
  - py.test -q QLiker.py
after_script:
  - nohup python QLiker.py >qbot.log&
  - sleep 60s
  - cat qbot.log
  - cat log.log
  - ls
  - killall python
